app/controllers/default.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash
from app import db
from app.models.tables import Cliente, Servico
import random as rd

# Cria um Blueprint para o módulo 'default'
default = Blueprint('default', __name__)

# Decorador que verifica se o usuário está logado
def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        # Redireciona pra página inicial se o usuário não estiver logado
        if 'username' not in session:
            return redirect(url_for('default.index'))
        return f(*args, **kwargs)
    return decorated_function

# Rota para a página inicial
@default.route('/', methods=['GET', 'POST'])
def index():
    # Se o método da requisição for POST
    if request.method == 'POST':
        print(request.form) # Imprime os dados do formulário no console
        
        # Verifica se o email foi enviado
        if 'email' in request.form:
            fullname = request.form['fullname'] # Obtém o nome completo
            username = request.form['username'] # Obtém o nome de usuário
            email = request.form['email'] # Obtém o e-mail
            password = request.form['password'] # Obtém a senha
            foto = rd.randint(0,19) # Obtém a senha
            
            # Verifica se o nome de usuário já existe no banco de dados
            user = Cliente.query.filter_by(username=username).first()
            if user:
                error = ['register','Esse nome de usuário já existe. Por favor, escolha outro.']
                return render_template('index.html', error=error) # Retorna erro na tela de registro
            else:
                # Verifica se o email já está em uso
                user = Cliente.query.filter_by(email=email).first()
                if user:
                    error = ['register','Esse E-mail já está sendo utilizado. Por favor, escolha outro.']
                    return render_template('index.html', error=error) # Retorna erro na tela de registro
                else:
                    # Cria um novo usuário se não houver conflitos
                    hashed_password = generate_password_hash(password) # Criptografa a senha
                    new_user = Cliente(fullname=fullname, username=username, email=email, senha=hashed_password, foto=foto)
                    db.session.add(new_user) # Adiciona o novo usuário à sessão do banco de dados
                    db.session.commit() # Salva as alterações no banco de dados
                    user = Cliente.query.filter_by(username=new_user.username).first_or_404() # Busca o usuário pelo nome
                    session['user_id'] = user.id  # Armazena o ID do usuário na sessão pra segurança
                    session['username'] = user.username  # Armazena o nome de usuário na sessão pra conveniência
                    session['perfil_photo'] = foto
                    return redirect(url_for('default.user', username=username)) # Redireciona pra página do usuário

                    services = Servico.query.filter_by(cliente_id=user.id).all() # Busca todos os serviços do cliente
                    print(user)
                    # Exibe a página do usuário com os serviços
                    return render_template('user.html', user=session['username'], services=services, username=username)
        else:
            # Processo de login
            username = request.form['username'] # Obtém o nome de usuário
            password = request.form['password'] # Obtém a senha
            user = Cliente.query.filter_by(username=username).first() # Busca o usuário pelo nome de usuário

            # Verifica se a senha está correta
            if user and check_password_hash(user.senha, password): 
                session['user_id'] = user.id  # Armazena o ID do usuário na sessão
                session['username'] = user.username  # Armazena o nome de usuário na sessão
                session['perfil_photo'] = user.foto
                return redirect(url_for('default.user', username=username)) # Redireciona para a página do usuário
            else:
                error = ['login','Nome de usuário ou senha incorretos.'] # Mensagem de erro se login falhar
                return render_template('index.html', error=error) # Retorna erro na tela de login
    else: # Se o método for GET
        if 'username' not in session:
            return render_template('index.html') # Exibe a página de login
        else:
            return redirect(url_for('default.user', username=session['username'])) # Redireciona pra página do usuário logado

# Rota para logout
@default.route('/logout')
def logout():
    session.clear() # Limpa a sessão do usuário
    return redirect(url_for('default.index')) # Redireciona pra página inicial

# Rota para a página do usuário
@default.route('/user/<username>', methods=['GET', 'POST', 'PUT'])
@login_required# Garante que o usuário esteja logado
def user(username):
    if request.method == 'POST': # Se o método da requisição for POST
        if '_method' in request.form: # Verifica se o formulário de edição de serviço foi enviado
            if request.form['_method'] == 'PUT':
                if 'service_id' in request.form:
                    client_id = session['user_id'] # Obtém o ID do cliente da sessão
                    user = Cliente.query.filter_by(id=client_id).first_or_404() # Busca o usuário pelo id
                    service = Servico.query.filter_by(name=request.form['service_name']).first() # Busca se tem serviços com o mesmo nome
                    print(request.form['service_id'])
                    print(service.id)
                    if int(service.id) != int(request.form['service_id']): # verifica se o serviços com o mesmo nome pertence cliente de id diferente
                        services = Servico.query.filter_by(cliente_id=client_id).all()
                        return render_template('user.html', username=session['username'], services=services, error=f'Já existe uma aplicação com o nome {request.form['service_name']}')
                    else:
                        service = Servico.query.filter_by(cliente_id=user.id, id=request.form['service_id']).first_or_404()# Busca todos os serviços do cliente
                        service.name = request.form['service_name'] # Obtém o nome do serviço
                        # Verifica quais opções foram selecionadas no formulário
                        if 'app_web' in request.form:
                            service.app_web = True
                        else:
                            service.app_web = False
                        if 'app_android' in request.form:
                            service.app_android = True
                        else:
                            service.app_android = False
                        if 'app_IOS' in request.form:
                            service.app_IOS = True
                        else:
                            service.app_IOS = False
                        if 'app_exe' in request.form:
                            service.app_exe = True
                        else:
                            service.app_exe = False

                        service.app_complex = request.form['app_complex'] # Obtém a complexidade da aplicação
                        service.app_obs = request.form['app_obs'] # Obtém observações sobre a aplicação
                        db.session.commit()
                        services = Servico.query.filter_by(cliente_id=client_id).all()
                        return render_template('user.html', username=session['username'], services=services)
            elif request.form['_method'] == 'DELETE':
                Servico.query.filter_by(id=request.form['service_id']).delete()
                services = Servico.query.filter_by(cliente_id=session['user_id']).all()
                db.session.commit()
                return render_template('user.html', username=session['username'], services=services, error=f'Aplicação excluída com sucesso!')

        # Verifica se o nome do serviço foi enviado
        if 'service_name' in request.form:
            service_name = request.form['service_name'] # Obtém o nome do serviço
            service = Servico.query.filter_by(name=service_name).first()

            # Verifica se o serviço já existe
            if service:
                error = ['service_name','Você já possui um serviço com esse nome. Por favor, escolha outro.']
                return render_template('user.html', error=error) # Retorna erro se o serviço já existir
            else:
                client_id = session['user_id'] # Obtém o ID do cliente da sessão
                user = Cliente.query.filter_by(id=client_id).first()
                # Verifica quais opções foram selecionadas no formulário
                if 'app_web' in request.form:
                    app_web = True
                else:
                    app_web = False
                if 'app_android' in request.form:
                    app_android = True
                else:
                    app_android = False
                if 'app_IOS' in request.form:
                    app_IOS = True
                else:
                    app_IOS = False
                if 'app_exe' in request.form:
                    app_exe = True
                else:
                    app_exe = False

                app_complex = request.form['app_complex'] # Obtém a complexidade da aplicação
                app_obs = request.form['app_obs'] # Obtém observações sobre a aplicação

                # Cria um novo serviço
                new_service = Servico(name=service_name, status='Pendente', cliente_id=user.id, app_web=app_web, app_android=app_android, app_IOS=app_IOS, app_exe=app_exe, app_complex=app_complex, obs=app_obs)
                db.session.add(new_service)
                db.session.commit()

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <title>Cloud Verse</title>
    <!--inclui arquivo css do bootstrap -->
    <!--inclui arquivo css pra icones do unicons a partir de uma url -->
    <!--inclui versão externa do css do bootstrap a partir de uma cdn -->
    <!--inclui arquivo css personalizado localizado na pasta do projeto -->
    <!-- Define as configurações de viewport para dispositivos móveis, ajustando a escala e o tamanho do conteúdo para se ajustar à tela -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v2.1.9/css/unicons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
  <!-- cria um elemento canvas com id rainfall pra animação de chuva, classe 'stars' pra estilização.  -->
  <canvas id="rainfall" class="stars"></canvas>
  <!-- fixa o conteúdo no topo da página durante o rolar -->
    <div class="sticky-top">
    <!-- Define uma barra de navegação com a classe navbar e um fundo escuro. O atributo data-bs-theme="dark" aplica um tema escuro para a barra de navegação. -->
      <nav class="navbar bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
      <!-- Conteiner para a logo da pagina -->
        <div class="logo_name_container">
        <!-- imagem da logo com a fonte definida com uma classe (logo_com_nome) pra estilização -->
          <img src="{{ url_for('static', filename='img/logo_com_nome1.png') }}" alt="Cloud Verse Logo" class="logo_com_nome">
        </div>
        <!-- cria um grupo de botoes adicional pro dropdown do usuario -->
        <div class="btn-group">
          {% if 'username' in session: %}
            <div class="btn-group">
              <!-- adiciona um manipulador de eventos Js para chamar a função toggleDropdown() quando clicado-->
              <!-- classe btn-usuario pra estilizar -->
              <button class ="btn-usuario" onclick="toggleDropdown()">{{ session['username'] }}
                <img src="{{ url_for('static', filename='img/perfil_' + session['perfil_photo']|string + '.png') }}", class="perfil_foto">


              </button>
              <!-- define o menu suspenso que aparece quando o botao é clicado -->
              <div class="dropdown-menu">
              <!-- link pra página de perfil (ainda nao tem) -->
                <a href="{{ url_for('default.index') }}">Perfil</a>
                <!-- link pra ação de logout com o destino -->
                <a href="{{ url_for('default.logout') }}">Sair</a>
              </div>              
            </div>
            <!-- Finaliza a verificação condicional pra autenticação do user-->
          {% endif %}
        </div>
      </nav>
    </div>
      <!-- Inicia a div 'extended-content' que vai ser preenchida com o conteúdo específico das páginas -->
      <div class="extended-content">
      <!-- Define um bloco de conteúdo onde o conteúdo específico de cada página vai ser inserido -->
        {% block content %}
        <!-- Finaliza o bloco de donteúdo -->
        {% endblock %}
      </div>
    <script>
        // Obtém o elemento canvas e seu contexto de renderização 2D
        const canvas = document.getElementById('rainfall');
        const ctx = canvas.getContext('2d');

        // Define o tamanho do canvas para coincidir com o tamanho da janela
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;

        // Array pra armazenar as gotas de chuva
        const raindrops = [];

        // Função pra criar uma nova gota de chuva 
        function createRaindrop() {
            // Gera posições aleatórias pra gota de chuva
            const x = Math.random() * canvas.width;
            const y = Math.random() * canvas.height;
            // Gera uma velocidade aleatória pra gota de chuva
            var velocity = Math.random() * 0.7 + 0.3;
            // Define a velocidade e direção da gota de chuva
            const speed = [[velocity, 0], [-velocity, 0]][Math.floor(Math.random() * 2)];

            //Define o comprimento e a cor da gota de chuva
            const length = 4;
            const color = ["#160518","#040125","#000f0e","#3b3544","#32293f","#5b457a","#120820","#242241","#2a574c","#2a3a57","#000000","#130022"][Math.floor(Math.random() * 13)];

            // Adiciona a nova gota de chuva ao array
            raindrops.push({ x, y, speed, length, color });
        }

        // Função pra atualizar as posições das gotas de chuva
        function updateRaindrops() {

            // Itera sobre cada gota de chuva
            for (let i = 0; i < raindrops.length; i++) {
                const raindrop = raindrops[i];

                // Atualiza a posição da gota de chuva com base na velocidade
                raindrop.y += raindrop.speed[0];
                raindrop.x += raindrop.speed[1];

                // Remove gotas de chuva que saíram da tela
                if (raindrop.y > canvas.height) {
                    raindrops.splice(i, 1); // Remove a gota do array
                    i--; // Ajusta o índice após a remoção
                }
            }
        }

        // Função pra desenhar as gotas de chuva no canvas
        function drawRaindrops() {

            // Limpa o canvas pra desenhar o próximo frame
            ctx.clearRect(0, 0, canvas.width, canvas.height);

            // Itera sobre cada gota de chuva
            for (let i = 0; i < raindrops.length; i++) {
              const raindrop = raindrops[i];

              // Define a cor da gota de chuva
              ctx.strokeStyle = raindrop.color;
              ctx.lineWidth = 4;
              ctx.beginPath();

              // Desenha a gota de chuva como uma linha vertical
              ctx.moveTo(raindrop.x, raindrop.y);
              ctx.lineTo(raindrop.x, raindrop.y + raindrop.length);
              ctx.stroke();
            }
        }

        // Função pra animar as gotas de chuva
        function animate() {
            createRaindrop(); // Cria novas gotas
            updateRaindrops(); // Atualiza a posição das gotas
            drawRaindrops(); // Desenha as gotas de chuva
            requestAnimationFrame(animate); // Solicita o próximo frame de animação
        }

        // Inicia a animação
        animate();
    </script>
    <script>
      // Função pra alternar a visibilidade do menu dropdown
      function toggleDropdown() {
        const dropdownMenu = document.querySelector('.dropdown-menu');

        // Alterna a exibição entre 'block' e 'none'
        dropdownMenu.style.display = dropdownMenu.style.display === 'block' ? 'none' : 'block';
      }
    
      // Adiciona um evento de clique no documento
      document.addEventListener('click', function(event) {
        const button = document.querySelector('.btn-usuario');
        const dropdownMenu = document.querySelector('.dropdown-menu');

        // Fechar o dropdown se clicar fora do botão ou fora do menu
        if (!button.contains(event.target) && !dropdownMenu.contains(event.target)) {
          dropdownMenu.style.display = 'none';
        }
      });
    </script>
  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="section">
    <div class="container_login">
        <div class="row full-height justify-content-center">
            <div class="col-12 text-center align-self-center py-5">
                <div class="section pb-5 pt-5 pt-sm-2 text-center">
                    <h6 class="mb-0 pb-3">
                        <span>Entrar </span><span> Registrar-se</span>
                    </h6>
                        <input class="checkbox" type="checkbox" id="reg-log" name="reg-log"/>
                        <label for="reg-log"></label>                      
                        <div class="card-3d-wrap mx-auto">
                            <div class="card-3d-wrapper">
                                <div class="card-front">
                                    <div class="center-wrap">
                                        <div class="section text-center">
                                            <form id="loginForm" method="POST" action="/">
                                            <h4 class="mb-4 pb-3">Entrar</h4>
                                            {% if error %}
                                                {% if error[0] == 'login': %}
                                                    <p class="error">{{ error[1] }}</p> 
                                                {% endif %}
                                            {% endif %}
                                            <div class="form-group">
                                                <input type="text" class="form-style" placeholder="Nome de usuário" id="username" name="username" required>
                                                <i class="input-icon uil uil-user"></i>
                                            </div>	
                                            <div class="form-group mt-2">
                                                <input type="password" class="form-style" placeholder="Senha" id="password" name="password" required>
                                                <i class="input-icon uil uil-lock-alt"></i>
                                            </div>
                                            <div class="remeber-forgot">
                                              <label class="custom-checkbox">
                                                <input type="checkbox" id="lembrar-me" name="lembrar-me">
                                                <span class="checkmark"></span> Lembrar-me
                                              </label>        
                                            </div>
                                            <button type="submit" class="btn mt-4">Entrar</button>
                                            <p class="mb-0 mt-4 text-center"></p> <a href="#">Esqueceu sua senha?</a>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-back">
                                    <div class="center-wrap">
                                        <div class="section text-center">
                                            <form id="registerForm" method="POST" action="/">
                                            <h4 class="mb-3 pb-3">Registrar-se</h4>
                                            {% if error %}
                                                {% if error[0] == 'register': %}
                                                    <p class="error">{{ error[1] }}</p> 
                                                {% endif %}
                                            {% endif %}
                                            <div class="form-group">
                                                <input type="text" class="form-style" placeholder="Nome Completo" id="fullname" name="fullname" required>
                                                <i class="input-icon uil uil-user"></i>
                                            </div>	
                                            <div class="form-group mt-2">
                                                <input type="text" class="form-style" placeholder="Nome de usuário" id="username" name="username" required>
                                                <i class="input-icon fas fa-hashtag"></i>
                                            </div>	
                                            <div class="form-group mt-2">
                                                <input type="email" class="form-style" placeholder="E-mail" id="email" name="email" required>
                                                <i class="input-icon uil uil-at"></i>
                                            </div>
                                            <div class="form-group mt-2">
                                                <input type="password" class="form-style" placeholder="Senha" id="password" name="password" required>
                                                <i class="input-icon uil uil-lock-alt"></i>
                                            </div>
                                            <button href="" class="btn mt-4" type="submit">Registrar</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/service_register.html
{% extends 'base.html' %}
{% block content %}
<div class="master">
    <div class="plan">
        <div class="inner">
            <p class="info">Atualmente você não possui serviços cadastrados. <br> Deseja adicionar um serviço?</p>
            <form id="register_service_Form" method="POST" action="{{ url_for('default.user', username=session['username']) }}">
                <ul class="features">
                    <h4 class="mb-3 pb-3">Registrar-se</h4>
                    {% if error %}
                        {% if error[0] == 'register': %}
                            <li>
                                <p class="error">{{ error[1] }}</p> 
                            </li>
                        {% endif %}
                    {% endif %}
                    <li>
                        <div class="form-group">
                            <input type="text" class="form-style" placeholder="Nome da aplicação" id="service_name" name="service_name" required>
                            <i class="input-icon uil uil-user"></i>
                        </div>
                    </li>
                    <li>
                        <label class="cyberpunk-checkbox-label">
                            <input type="checkbox" class="cyberpunk-checkbox" id="app_web" name="app_web">
                            <span><strong>Website </strong></span>(html/css/js)
                        </label>
                    </li>
                    <li>
                        <label class="cyberpunk-checkbox-label">
                            <input type="checkbox" class="cyberpunk-checkbox" id="app_android" name="app_android">
                            <span><strong>Aplicativo </strong>(Android)</span>
                        </label>
                    </li>
                    <li>
                        <label class="cyberpunk-checkbox-label">
                            <input type="checkbox" class="cyberpunk-checkbox" id="app_IOS" name="app_IOS">
                            <span> <strong>Aplicativo </strong>(IOS)</span>
                        </label>
                    </li>
                    <li>
                        <label class="cyberpunk-checkbox-label">
                            <input type="checkbox" class="cyberpunk-checkbox" id="app_exe" name="app_exe">
                            <span><strong>Executável </strong>(Windows)</span>
                        </label>
                    </li>
                    <li>
                        <div class="form-group">
                            <input type="text" class="form-style" placeholder="Detalhes..." id="app_obs" name="app_obs" required>
                            <i class="input-icon uil uil-user"></i>
                        </div>
                    </li>
                    <li>
                        <label class="cyberpunk-checkbox-label">
                            <span><strong>Complexidade</strong> da aplicação.</span>
                        </label>
                        
                    </li>
                    <li>
                        <input id="app_complex" name="app_complex" class="slider" value="50" max="100" min="0" type="range">
                    </li>
                </ul>
                <button class="button" type="submit" href="">Solicitar Aplicação</button>
            </form>

        </div>
    </div>
</div>
{% endblock %}